export const TITLES = [
  {
    games: null,
    min_time: null,
    rating: 2600,
    required_rating: null,
    sex: "M",
    title: "GM",
  },
  {
    games: null,
    min_time: null,
    rating: 2450,
    required_rating: null,
    sex: "M",
    title: "IM",
  },
  {
    games: null,
    min_time: null,
    rating: 2300,
    required_rating: null,
    sex: "M",
    title: "FM",
  },
  {
    games: null,
    min_time: null,
    rating: 2200,
    required_rating: null,
    sex: "M",
    title: "CM",
  },
  {
    games: 9,
    min_time: 120,
    rating: 2400,
    required_rating: 2400,
    sex: "M",
    title: "M",
  },
  {
    games: 9,
    min_time: 120,
    rating: 2300,
    required_rating: null,
    sex: "M",
    title: "K++",
  },
  {
    games: 9,
    min_time: 120,
    rating: 2300,
    required_rating: null,
    sex: "M",
    title: "K+",
  },
  {
    games: 9,
    min_time: 90,
    rating: 2200,
    required_rating: 2200,
    sex: "M",
    title: "K",
  },
  {
    games: 9,
    min_time: 90,
    rating: 2100,
    required_rating: null,
    sex: "M",
    title: "I++",
  },
  {
    games: 9,
    min_time: 90,
    rating: 2100,
    required_rating: null,
    sex: "M",
    title: "I+",
  },
  {
    games: 9,
    min_time: 90,
    rating: 2000,
    required_rating: 2000,
    sex: "M",
    title: "I",
  },
  {
    games: 9,
    min_time: 90,
    rating: 1900,
    required_rating: null,
    sex: "M",
    title: "II+",
  },
  {
    games: 7,
    min_time: 60,
    rating: 1800,
    required_rating: 1800,
    sex: "M",
    title: "II",
  },
  {
    games: 7,
    min_time: 60,
    rating: 1600,
    required_rating: 1550,
    sex: "M",
    title: "III",
  },
  {
    games: 5,
    min_time: 30,
    rating: 1400,
    required_rating: 1300,
    sex: "M",
    title: "IV",
  },
  {
    games: 5,
    min_time: 30,
    rating: 1200,
    required_rating: 1050,
    sex: "M",
    title: "V",
  },
  {
    games: null,
    min_time: null,
    rating: 1000,
    required_rating: null,
    sex: "M",
    title: "bk",
  },
  {
    games: null,
    min_time: null,
    rating: 2400,
    required_rating: null,
    sex: "F",
    title: "WGM",
  },
  {
    games: null,
    min_time: null,
    rating: 2250,
    required_rating: null,
    sex: "F",
    title: "WIM",
  },
  {
    games: null,
    min_time: null,
    rating: 2100,
    required_rating: null,
    sex: "F",
    title: "WFM",
  },
  {
    games: null,
    min_time: null,
    rating: 2000,
    required_rating: null,
    sex: "F",
    title: "WCM",
  },
  {
    games: null,
    min_time: null,
    rating: 2600,
    required_rating: null,
    sex: "F",
    title: "GM",
  },
  {
    games: null,
    min_time: null,
    rating: 2450,
    required_rating: null,
    sex: "F",
    title: "IM",
  },
  {
    games: null,
    min_time: null,
    rating: 2300,
    required_rating: null,
    sex: "F",
    title: "FM",
  },
  {
    games: null,
    min_time: null,
    rating: 2200,
    required_rating: null,
    sex: "F",
    title: "CM",
  },
  {
    games: 9,
    min_time: 120,
    rating: 2200,
    required_rating: 2200,
    sex: "F",
    title: "M",
  },
  {
    games: 9,
    min_time: 120,
    rating: 2100,
    required_rating: null,
    sex: "F",
    title: "K++",
  },
  {
    games: 9,
    min_time: 120,
    rating: 2100,
    required_rating: null,
    sex: "F",
    title: "K+",
  },
  {
    games: 9,
    min_time: 90,
    rating: 2000,
    required_rating: 2000,
    sex: "F",
    title: "K",
  },
  {
    games: 9,
    min_time: 90,
    rating: 1900,
    required_rating: null,
    sex: "F",
    title: "I++",
  },
  {
    games: 9,
    min_time: 90,
    rating: 1900,
    required_rating: null,
    sex: "F",
    title: "I+",
  },
  {
    games: 7,
    min_time: 60,
    rating: 1800,
    required_rating: 1800,
    sex: "F",
    title: "I",
  },
  {
    games: 7,
    min_time: 60,
    rating: 1700,
    required_rating: null,
    sex: "F",
    title: "II+",
  },
  {
    games: 7,
    min_time: 60,
    rating: 1600,
    required_rating: 1600,
    sex: "F",
    title: "II",
  },
  {
    games: 7,
    min_time: 30,
    rating: 1400,
    required_rating: 1350,
    sex: "F",
    title: "III",
  },
  {
    games: 5,
    min_time: 30,
    rating: 1250,
    required_rating: 1150,
    sex: "F",
    title: "IV",
  },
  {
    games: 5,
    min_time: 30,
    rating: 1100,
    required_rating: 1000,
    sex: "F",
    title: "V",
  },
  {
    games: null,
    min_time: null,
    rating: 1000,
    required_rating: null,
    sex: "F",
    title: "bk",
  },
];

export const RESULTS = ["1", "0", "=", "+", "-", "P"] as const;
